### ISSUE TITLE
Make a buildable source 

### ISSUE THREAD

**Issue by OLD-H28EVR** [3000IQPlay/RavenBMinus-Cracked#1]
Make one so we can remove auth and skid from it

**Comment by 3000IQPlay** [comment]
> Make one so we can remove auth and skid from it

I prob wont since the client is broken and wont launch even in its original obfed form + i dont want to fix all of the issues

**Comment by StephenIsTaken** [comment]
> > Make one so we can remove auth and skid from it
> 
> I prob wont since the client is broken and wont launch even in its original obfed form + i dont want to fix all of the issues

Ok
