### ISSUE TITLE
Now that it works make a buildable source.

### ISSUE THREAD

**Issue by OLD-H28EVR** [3000IQPlay/RavenBMinus-Cracked#2]
Cmon.....

**Comment by StephenIsTaken** [comment]
If you do this we can annoy Jors and Mitfox even more !!

**Comment by Cosmic-SC** [comment]
brr its a pain ive looked at the code and the obfuscation is just AHHHHHHHHHHHHHH

**Comment by 3000IQPlay** [comment]
Fr
